=== davide-dascanio/Tesina-Linguaggi-Web/xml/storico_acquisti.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
  <xs:element name="acquisti">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="acquisto" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="data" type="xs:date"/>
              <xs:element name="ora" type="xs:time"/>
              <xs:element name="id_prodotto" type="xs:integer"/>
              <xs:element name="nome_prodotto" type="xs:string"/>
              <xs:element name="prezzo_unitario" type="xs:decimal"/>
              <xs:element name="quantita" type="xs:integer"/>
              <xs:element name="prezzo_scontato" type="xs:decimal"/>
              <xs:element name="bonus" type="xs:deciaml"/>
              <xs:element name="prezzo_totale" type="xs:decimal"/>
            </xs:sequence>
            <xs:attribute name="id_utente" type="xs:integer" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
    
</xs:schema>

=== davide-dascanio/Tesina-Linguaggi-Web/xml/storico_acquisti.xml
<?xml version="1.0" encoding="UTF-8"?>
<acquisti xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="storico_acquisti.xsd">
  <acquisto id_utente="4">
    <data>2026-04-01</data>
    <ora>20:19:55</ora>
    <id_prodotto>1</id_prodotto>
    <nome_prodotto>Samsung Crystal UHD 50</nome_prodotto>
    <prezzo_unitario>500.00</prezzo_unitario>
    <quantita>1</quantita>
    <prezzo_scontato>450.00</prezzo_scontato>
    <bonus>9</bonus>
    <prezzo_totale>450.00</prezzo_totale>
  </acquisto>
  <acquisto id_utente="4">
    <data>2026-04-01</data>
    <ora>20:20:12</ora>
    <id_prodotto>8</id_prodotto>
    <nome_prodotto>Vogel Supporto TV Orientabile</nome_prodotto>
    <prezzo_unitario>79.00</prezzo_unitario>
    <quantita>1</quantita>
    <prezzo_scontato>79.00</prezzo_scontato>
    <bonus>0</bonus>
    <prezzo_totale>79.00</prezzo_totale>
  </acquisto>
  <acquisto id_utente="5">
    <data>2026-04-01</data>
    <ora>20:22:35</ora>
    <id_prodotto>4</id_prodotto>
    <nome_prodotto>Sony Soundbar HT-S100F</nome_prodotto>
    <prezzo_unitario>129.25</prezzo_unitario>
    <quantita>1</quantita>
    <prezzo_scontato>122.79</prezzo_scontato>
    <bonus>0</bonus>
    <prezzo_totale>122.79</prezzo_totale>
  </acquisto>
  <acquisto id_utente="5">
    <data>2026-04-01</data>
    <ora>20:22:35</ora>
    <id_prodotto>7</id_prodotto>
    <nome_prodotto>Meliconi Supporto TV da parete Slim</nome_prodotto>
    <prezzo_unitario>39.99</prezzo_unitario>
    <quantita>1</quantita>
    <prezzo_scontato>39.99</prezzo_scontato>
    <bonus>0</bonus>
    <prezzo_totale>39.99</prezzo_totale>
  </acquisto>
</acquisti>
